// Generated by build/generate.mjs — do not edit by hand.
export const ROUTES = {
  "wheel": {
    "slug": "wheel-of-names",
    "title": "Wheel of Names — Free Random Name Picker | SpinDecks",
    "description": "Spin a free wheel of names with no ads and no sign-up. Multiple wheels, images, weighted entries, elimination mode and fair no-repeat picking. Works offline."
  },
  "groups": {
    "slug": "random-team-generator",
    "title": "Random Team Generator — Free Group Maker | SpinDecks",
    "description": "Split a list into random teams or groups instantly. Set team size or team count, reuse your saved lists, and re-roll for a fresh shuffle. Free, ad-free, no login."
  },
  "scores": {
    "slug": "darts-scoreboard",
    "title": "Darts Scoreboard — Free Online 501 & Cricket Scorer | SpinDecks",
    "description": "Free online darts scoreboard for 501 and cricket. Track multiple players, bust handling and running totals on any device. No ads, no sign-up, works offline."
  },
  "numbers": {
    "slug": "random-number-generator",
    "title": "Random Number Generator — Pick a Number in a Range | SpinDecks",
    "description": "Generate random numbers in any range, with or without repeats. Draw one or many at once, flip a coin or roll dice. Free, ad-free, no sign-up, works offline."
  },
  "timer": {
    "slug": "countdown-timer",
    "title": "Countdown Timer — Free Classroom & Stream Timer | SpinDecks",
    "description": "A big, clear countdown timer for lessons, tasks and streams. Quick presets, custom times, stopwatch mode and an optional end beep. Free, ad-free, no login."
  },
  "counter": {
    "slug": "tally-counter",
    "title": "Tally Counter — Free Online Click Counter | SpinDecks",
    "description": "Free online tally counter. Run several counters at once, set custom steps, and reset with one tap. Ad-free, no sign-up, works offline on phone or desktop."
  },
  "slots": {
    "slug": "slot-machine",
    "title": "Slot Reels — Random Picker with Spinning Reels | SpinDecks",
    "description": "A slot-reel style random picker. Feed it your own list and let the reels decide. Free, ad-free and offline — a fun alternative to a spinning wheel."
  },
  "dice": {
    "slug": "dice-roller",
    "title": "Dice Roller — Roll 3d6, d20 & Any Dice Notation | SpinDecks",
    "description": "Free online dice roller with standard notation: 3d6+2, 4d6kh3, 2d20kh1. Roll any dice for RPGs and board games. Fair, fast, ad-free, works offline."
  },
  "firstplayer": {
    "slug": "first-player-picker",
    "title": "Who Goes First? Free First Player Picker | SpinDecks",
    "description": "Decide who goes first in seconds. Tap for a random player, or generate a full random turn order. Multi-touch “finger” picker for phones at the table. Free, ad-free."
  },
  "scorepad": {
    "slug": "scorepad",
    "title": "Score Pad — Free Board Game Score Keeper | SpinDecks",
    "description": "A free score pad for any board or card game. Add players, score by round, see running totals. Big keypad for phones, undo, and screen-awake. No ads, no login."
  },
  "chessclock": {
    "slug": "chess-clock",
    "title": "Online Chess Clock — Free 2-Player & Multiplayer Timer | SpinDecks",
    "description": "A free online chess clock and game timer for two players or up to six. Each player gets a time bank; tap your area to end your turn, with optional Fischer increment. No ads, no sign-up, works offline."
  },
  "bracket": {
    "slug": "tournament-bracket",
    "title": "Tournament Bracket Generator — Knockout, League & Groups | SpinDecks",
    "description": "Free tournament bracket generator: single-elimination knockout, round-robin league tables, or group stages into a knockout. Random or ordered seeding. No ads, no sign-up."
  },
  "dojo": {
    "slug": "bt-dojo",
    "title": "The BT Dojo — Head-to-Head Classroom Quiz Game | SpinDecks",
    "description": "A fast two-player classroom quiz game for the interactive whiteboard. Winner stays on, lives and powerups, a class leaderboard, and any question set you choose. Free, no sign-up, works offline."
  },
  "reveal": {
    "slug": "reveal-cards",
    "title": "Reveal Cards — Free Classroom Flashcards for the Whiteboard | SpinDecks",
    "description": "A teacher-paced flashcard runner for the interactive whiteboard. Show a question, reveal the answer when the class is ready, move on. Uses any question set. Free, no sign-up, works offline."
  },
  "pairs": {
    "slug": "pairs",
    "title": "Pairs — Free Classroom Matching & Memory Game | SpinDecks",
    "description": "A match-the-answer memory game for the whiteboard. Flip cards to pair each question with its answer, solo or in two teams. Uses any question set. Free, no sign-up, works offline."
  },
  "bingo": {
    "slug": "bingo",
    "title": "Classroom Bingo — Free Question Bingo Caller & Card Maker | SpinDecks",
    "description": "Whole-class bingo for the whiteboard. You call the questions, students mark the answers on their cards. Print cards from any question set and reveal answers one at a time. Free, no sign-up, works offline."
  },
  "classquiz": {
    "slug": "class-quiz",
    "title": "Class Quiz — Free Team Quiz Game for the Whiteboard | SpinDecks",
    "description": "Run a team quiz on the whiteboard. Split the class into teams (from a saved wheel if you like), reveal each answer and tap the team that got it — scores keep themselves. Free, no sign-up, works offline."
  },
  "gridclaim": {
    "slug": "grid-claim",
    "title": "Grid Claim — Free Two-Team Connect Quiz Game | SpinDecks",
    "description": "A two-team connect game for the whiteboard. Answer questions to claim tiles — one team joins left to right, the other top to bottom. First to bridge their sides wins. Free, no sign-up, works offline."
  },
  "countdown": {
    "slug": "countdown",
    "title": "Countdown Game — Free Letters, Numbers & Conundrum | SpinDecks",
    "description": "The classic letters, numbers and conundrum game for the whiteboard. Pick your letters, reach the target number, or crack the nine-letter conundrum — each with a 30-second clock. Free, no sign-up, works offline."
  }
};

