// Generated by build/generate.mjs — do not edit by hand.
export const ROUTES = {
  "wheel": {
    "slug": "wheel-of-names",
    "title": "Wheel of Names — Free Random Name Picker | SpinDecks",
    "description": "Spin a free wheel of names with no ads and no sign-up. Multiple wheels, images, weighted entries, elimination mode and fair no-repeat picking. Works offline."
  },
  "groups": {
    "slug": "random-team-generator",
    "title": "Random Team Generator — Free Group Maker | SpinDecks",
    "description": "Split a list into random teams or groups instantly. Set team size or team count, reuse your saved lists, and re-roll for a fresh shuffle. Free, ad-free, no login."
  },
  "scores": {
    "slug": "darts-scoreboard",
    "title": "Darts Scoreboard — Free Online 501 & Cricket Scorer | SpinDecks",
    "description": "Free online darts scoreboard for 501 and cricket. Track multiple players, bust handling and running totals on any device. No ads, no sign-up, works offline."
  },
  "numbers": {
    "slug": "random-number-generator",
    "title": "Random Number Generator — Pick a Number in a Range | SpinDecks",
    "description": "Generate random numbers in any range, with or without repeats. Draw one or many at once, flip a coin or roll dice. Free, ad-free, no sign-up, works offline."
  },
  "timer": {
    "slug": "countdown-timer",
    "title": "Countdown Timer — Free Classroom & Stream Timer | SpinDecks",
    "description": "A big, clear countdown timer for lessons, tasks and streams. Quick presets, custom times, stopwatch mode and an optional end beep. Free, ad-free, no login."
  },
  "counter": {
    "slug": "tally-counter",
    "title": "Tally Counter — Free Online Click Counter | SpinDecks",
    "description": "Free online tally counter. Run several counters at once, set custom steps, and reset with one tap. Ad-free, no sign-up, works offline on phone or desktop."
  },
  "slots": {
    "slug": "slot-machine",
    "title": "Slot Reels — Random Picker with Spinning Reels | SpinDecks",
    "description": "A slot-reel style random picker. Feed it your own list and let the reels decide. Free, ad-free and offline — a fun alternative to a spinning wheel."
  },
  "dice": {
    "slug": "dice-roller",
    "title": "Dice Roller — Roll 3d6, d20 & Any Dice Notation | SpinDecks",
    "description": "Free online dice roller with standard notation: 3d6+2, 4d6kh3, 2d20kh1. Roll any dice for RPGs and board games. Fair, fast, ad-free, works offline."
  }
};

